Refactor/updatetousectxbroker
diwise/ingress-trafikverket pull request #7
Opened 2022-12-22 16:11 UTC by shestyf

2022-12-22 17:05 UTC, istyf requested changes

2022-12-22 17:05 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
> +		logger.Error().Err(err).Msg("failed to create attribute for fiware entity")
Du kan inte fortsätta här om det inte skapades några attributes, väl?

2022-12-22 17:05 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
> +			logger.Error().Err(err).Msg("failed to merge entity")
Vill vi verkligen gå vidare och försöka göra en create om vi får ett okänt fel när vi försöker merga?

2022-12-22 17:05 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
> +			logger.Error().Err(err).Msg("entities.New failed")
Igen. Det räcker inte att logga ett fel, du måste hantera det.

2022-12-22 17:05 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
> +		make([]entities.EntityDecoratorFunc, 0, 2),
Allokera plats för så många som det kan bli, inte så många som det minst är. 2 -> 6

2022-12-22 17:05 UTC, istyf commented on internal/pkg/application/services/roadaccidents/roadaccidents_test.go
> +//const roadAccidentJSON string = `{"id":"urn:ngsi-ld:RoadAccident:SE_STA_TRISSID_1_16279394","type":"RoadAccident","@context":["https://raw.githubusercontent.com/smart-data-models/dataModel.Transpor
Varför används inte den här längre? Behöver den vara kvar?

2022-12-22 17:05 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
> +		attributes = append(attributes, decorators.DateModified(time.Now().UTC().Format(time.RFC3339)))
Det här ser skumt ut. Anger vi inte på något annat sätt att den är deleted? Borde vi göra en DELETE på den här entiteten i stället?

2023-01-02 09:40 UTC, shestyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
> +		attributes = append(attributes, decorators.DateModified(time.Now().UTC().Format(time.RFC3339)))
Jag tänker att det beror på. Vi har tidigare bara patch-at status på incidents som har blivit borttagna. Men vi kanske inte vill göra så längre om vi nu har möjlighet att ta bort istället.

2023-01-02 10:35 UTC, shestyf commented on internal/pkg/application/services/roadaccidents/roadaccidents_test.go
> +//const roadAccidentJSON string = `{"id":"urn:ngsi-ld:RoadAccident:SE_STA_TRISSID_1_16279394","type":"RoadAccident","@context":["https://raw.githubusercontent.com/smart-data-models/dataModel.Transpor
Nej, den behövs inte.

2023-01-09 06:58 UTC, istyf requested changes

2023-01-09 06:58 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
> +		attributes = append(attributes, decorators.DateModified(time.Now().UTC().Format(time.RFC3339)))
Det här blir hur som helst fel. Ta bort hela if deleted tills du vet vad du skall göra i det läget.

2023-01-09 06:58 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
>  	Longitude := strings.Split(position, " ")[0]
longitude

2023-01-09 06:58 UTC, istyf commented on internal/pkg/application/services/roadaccidents/publishroadaccidents.go
>  	Latitude := strings.Split(position, " ")[1]
latitude

2023-01-09 06:58 UTC, istyf commented on internal/pkg/application/services/roadaccidents/roadaccidents.go
> +	publishRoadAccidentToContextBroker(ctx context.Context, dev tfvDeviation, deleted bool) error
Varför har vi funktioner som är package private i ett interface?

2023-01-09 09:26 UTC, istyf approved these changes
/lgtm

2023-01-09 09:27 UTC, merged